# main config file
[server]
type = ""                                            # http2 server always
mux = "gin"                                          # might be: iris, echo, gin, gorilla, default, ...
port = 9477
ports = { tls = 9479, debug = 9478, default = 9477 }
addr = ""                                            # default is "0.0.0.0" or ipv4 "*"

[server.addresses]
rpc = ""
advertise = ""

[server.auto-cert]
enabled = false
domains = ["example.com"]
domains-2nd-level = ["aurora", "api", "home", "res"]

# used by certtool.XsTLSConfig
[server.tls.certs]
# enabled = true
ca-cert = ""             # ca.pem (the implicit key file is ca.pem.key)
server-cert = ""         # server.pem (another implicit file is server-bundle.pem)
cert = ""                # cert.pem
key = ""                 # key.pem
client-auth = false      #
min-tls-version = 0x0304 # 0x0304 = v1.3, 0x0303 = v1.2, ...

[server.statics]
assets = { url = "/assets", path = "./static/assets" }
templates = { path = "./static/templates", pattern = "*.tmpl", left = "{{", right = "}}" }
